# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('viewflow', '0005_rename_flowcls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('more_info', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
